== Sonstige Qualitätsanforderungen

Da hätten wir noch eine nahezu beliebige Menge weiterer Qualitätsanforderungen, beispielsweise Funktionalität. Oder diverse Synonyme bereits vorgestellter Q-Merkmale :-)

Einige Definitionen:

=== Funktionalität:

Vorhandensein von Funktionen mit festgelegten Eigenschaften; diese Funktionen erfüllen die definierten Anforderungen. Zu Funktionalität gehören nach DIN/ISO 9126 noch folgende Teilmerkmale:

*Richtigkeit*:: Liefern der richtigen oder vereinbarten Ergebnisse oder Wirkungen, z.B. die benötigte Genauigkeit von berechneten Werten.
*Angemessenheit*:: Eignung der Funktionen für spezifizierte Aufgaben, z.B. aufgaben-orientierte Zusammensetzung von Funktionen aus Teilfunktionen.
*Interoperabilität*:: Fähigkeit, mit vorgegebenen Systemen zusammenzuwirken. Hierunter fällt auch die Einbettung in die Betriebsinfrastruktur.
*Ordnungsmäßigkeit*:: Erfüllung von anwendungsspezifischen Normen, Vereinbarungen, gesetzlichen Bestimmungen und ähnlichen Vorschriften.


=== Sonstige Szenarien

==== Szenario: Verfügbarkeit für unterschiedliche Datenbanksysteme
Das System (Werkzeug) dient zur Performancemessung für Datenbanksysteme. 
Es muss für unterschiedliche Datenbanksysteme zur Verfügung stehen. 

[horizontal]
Geschäftsziel::
Portabilität, Effizienz, Betreibbarkeit.
Vielseitiges Werkzeug, soll für unterschiedliche Datenbanksysteme zur Verfügung stehen

Auslöser::
Das Werkzeug wird (per Dialog, Kommandozeile oder programmatisch) mit einem Datenbanksystem verbunden ("connected"): Oracle, DB2, Sybase, MySQL, PostgreSQL

Reaktion::
Das Werkzeug stellt die Verbindung zum jeweiligen DBMS erfolgreich her - im Werkzeug ist die DB-Struktur sichtbar.

Zielwert::
Der "connect" zur Datenbank erfolgt innerhalb von 30 Sekunden.

==== Szenario: Kernfunktion portabel auf iOS und Android
Die Kernfunktionen der Mac-OS Software können unter iOS und Android wiederverwendet werden. 

[horizontal]
Qualitätsziele:: 
Wiederverwendbarkeit, Austauschbarkeit

Geschäftsziel::
Schnelle Time-to-Market, reduzierte Entwicklungskosten, Marktvergrößerung

Auslöser::
Code ist für Mac-OS entwickelt

Reaktion::
Der Code ist weitmöglich (soweit die Technologie das zulässt) sowohl unter iOS und Android wieder verwendbar.

Zielwert::
Das Entwicklungsteam soll die Kernfunktionen wiederverwenden, ohne sie komplett neu implementieren beziehungsweise entwerfen zu müssen.

Ausnahme hiervon sind direkte Aufrufe der jeweiligen Betriebssystemfunktionen.


==== Szenario: 60% Testabdeckung für Unit-Tests. 

[horizontal]
Qualitätsziele:: Testbarkeit, Änderbarkeit

Geschäftsziel::
Einfache Erweiter- und Änderbarkeit durch hohe Testabdeckung, schnelle Rückmeldung über mögliche Nebenwirkungen bei Codeänderungen.

Auslöser::
Entwickler entwickelt oder ändert eine Funktion / Methode / Klasse.

Reaktion::
Die betroffene Funktion / Methode / Klasse wird durch Unit-Tests überprüft.

Zielwert::
Über 60% Pfadabdeckung wird durch die Unit-Tests erreicht.


==== Szenario: Einfaches Hinzufügen neuer Tests. 
Tester sollen mit geringem Aufwand neue Tests zu bestehenden Testsuites hinzufügen können.

[horizontal]
Qualitätsziele:: Testbarkeit, Änderbarkeit

Geschäftsziel::
Fähigkeit, neue Tests einfach in bestehende Test-Suites zu integrieren.

Auslöser::
Tester möchte neuen Test zu einer bestehenden Testsuite hinzufügen 

Reaktion::
Der Test wird zugefügt ohne den Code des Systems selbst (d.h. Den Produktivcode) zu modifizieren.

Zielwert::
Es ist kein Re-Compile oder Neukonfiguration des Systems (genauer: des Produktivcodes) nötig.

Anmerkung:: Testcode oder Testkonfigurationen dürfen jedoch verändert werden.



==== Szenario: Ähnliche Resultate bei stochastischen Testreihen
Werden zwei stochastische Testreihen ausgeführt, sind die Resultate zu 90% ähnlich.

[horizontal]
Qualitätsziele:: Testbarkeit, Konsistenz, Nachvollziehbarkeit. 
Konsistente Testergebnisse auch bei stochastischen Tests oder Testreihen.

Auslöser::
Testszenario oder Testreihe mit Anteil an zufällig bestimmten Testdaten wird ausgeführt 

Reaktion::
Ähnliche Testergebnisse.

Zielwert::
Die Ergebnisse zweier Testreihen sind bei 90% aller Einzeltests ähnlich.

==== Szenario: Testausführung mit einzelnem Befehl
Ein Tester möchte mehrere Testszenarien mit einem einzelnen Befehl durchführen können. 


[horizontal]
Geschäftsziel::
Effizienz, Testbarkeit 

Auslöser::
Testadministrator oder Tester möchte mehrere Tests oder Testszenarien durchführen 

Reaktion::
Aggregation oder Hintereinander-Ausführung mehrerer Tests.

Zielwert::
Ausführung mehrerer Tests benötigt nur einen einzigen Befehl des Testers oder Testadministrators.


==== Szenario: X-Daten für externe Systeme zugänglich
Die X-Daten des Y-Systems sollen für ein externes Werkzeug zur Anforderungsanalyse und -management (etwa: Requisite-Pro, Enterprise-Architect oä) zugänglich sein. 

[horizontal]
Qualitätsziel:: Interoperabilität

Geschäftsziel(e)::
Datenkompatibilität mit marktüblichen Werkzeugen zur Anforderungsanalyse zählt als Vorteil gegenüber Mitbewerbern.

Auslöser::
Ein Endbenutzer möchte die X-Daten des Y-Systems in eines der unterstützten Anforderungstools überführen. 

Kontext::
20 Benutzer haben X-Daten in Form einzelner Projekte im System erfasst.
Jedes dieser Projekte enthält mindestens ein, höchstens 100 unterschiedliche Requirements.

Reaktion::
Das Y-System exportiert die betreffenden X-Daten in das Anforderungstool (Requisite-Pro oder Enterprise-Architect).

Zielwert::
* Beim Export der Daten treten keine Fehler auf.
* Von den im Y-System enthaltenen Requirements werden mindestens 98% korrekt exportiert.
* Sämtliche nicht exportierten Requirements werden den betroffenen Benutzern als Fehler gemeldet.


